import * as key from './KeyCodes'

export const TextCode = {
    'acos' : key.ACOS,
    'add': key.ADD,
    '+' : key.ADD,
    'arc' : key.ARC,
    'asin' : key.ASIN,
    'atan' : key.ATAN,
    'chs': key.CHS,
    '±': key.CHS,
    'clr' : key.CLR,
    'clx' : key.CLX,
    'cos' : key.COS,
    'div': key.DIV,
    '/': key.DIV,
    'eex' : key.EEX,
    'enter': key.ENTER,
    '='    : key.ENTER,
    'exp' : key.EXP,
    'ln' : key.LN,
    'log' : key.LOG,
    'mul': key.MUL,
    '*' : key.MUL,
    'pi' : key.PI,
    'pow': key.POW,
    'y^x' :key.POW,
    'rcl' : key.RCL,
    'reciprocal' : key.RECIPROCAL,
    'rolldown' : key.ROLL_DOWN,
    'sin' : key.SIN,
    'sqrt' : key.SQRT,
    'sto' : key.STO,
    'sub': key.SUB,
    '-': key.SUB,
    'swap' : key.SWAP,
    'tan' : key.TAN,
}


